# Generated by Django 4.2.4 on 2023-08-08 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Topic',
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'topic', 'verbose_name_plural': 'topics'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='type',
        ),
        migrations.AddField(
            model_name='comment',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='comment', to='forum.topic', verbose_name='topic'),
        ),
    ]
